# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdds-dev
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:9000"
    command:
      - 'php'
      - '-S'
      - '[::]:9000'
      - '-t'
      - '/var/www/html'
